
[package]
# Semantic Versioning is used: https://semver.org/
version = "0.1.0"
authors = ["Ten Minute Physics"]
title = "Fun"
description="Ten Minute Physics domniverse extension"
readme  = "docs/README.md"
repository="https://github.com/matthias-research/omni.fun"
category = "sim"
keywords = ["simulation"]
changelog="docs/CHANGELOG.md"

preview_image = "data/preview.png"
icon = "data/icon.png"

# Watch the .ogn files for hot reloading (only works for Python files)
[fswatcher.patterns]
include = ["*.ogn", "*.py"]
exclude = ["Ogn*Database.py", "*/ogn*"]

[dependencies]
"omni.kit.test" = {}
"omni.kit.menu.utils" = {}
"omni.timeline" = {}
"omni.usd" = {}

# Main python module this extension provides, it will be publicly available as "import omni.play".
[[python.module]]
name = "omni.fun"

# Core language module
[[python.module]]
name = "fun"
path = "."
public = true